以下是修改后的 GitHub Actions 工作流文件，在安装依赖项步骤中增加了 Python-pip 的安装：

name: Run_Adblock_Reject_JSON19  # Workflow name

on:
  schedule:
    - cron: '* * 2 * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 版本作为运行器

    steps:
    - name: Setup Node.js 20  # 设置 Node.js 20 环境
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # 指定 Node.js 版本 20

    - name: Setup Python 3.9  # 设置 Python 3.9 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 指定 Python 版本 3.9

    - name: Checkout repository  # 检出代码仓库
      uses: actions/checkout@v3

    - name: Install dependencies and sing-box  # 安装依赖项和 sing-box
      run: |
        sudo apt-get update  # 更新软件包列表
        sudo apt-get install -y wget apt-transport-https software-properties-common  # 安装必要工具
        wget https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box-1.11.15-linux-amd64.tar.gz
        tar -zxvf sing-box-1.11.15-linux-amd64.tar.gz
        sudo apt install -y bash
        sudo apt install -y python3-pip  # 显式安装 Python3-pip
        pip3 install --upgrade pip  # 升级 pip 到最新版本
        pip3 install requests  # 使用 pip3 安装依赖库
        rm sing-box-1.11.15-linux-amd64.tar.gz  # 清理下载文件

    - name: Run adblock_rule_generator_json19.py  # 运行 Python 脚本
      run: python3 adblock_rule_generator_json19.py  # 显式使用 Python3 执行脚本

    - name: Convert rule-set  # 转换规则集
      shell: bash
      run: sing-box-1.11.15-linux-amd64/sing-box rule-set compile --output adblock_reject19.srs adblock_reject19.json

    - name: Force Add and Commit adblock_rule_generator_json19.srs  # 强制添加并提交文件
      run: |
        git config --global user.name 'github-actions'  # 配置 Git 用户名
        git config --global user.email 'github-actions@github.com'  # 配置 Git 邮箱
        git add -f adblock_reject19.srs  # 强制添加文件
        git commit -m 'Update adblock_reject19.srs' || true  # 提交变更（允许空提交）

    - name: Retry Push SRS file  # 重试推送文件
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 密钥进行身份验证
      run: |
        for i in {1..5}; do  # 最多重试5次
          git push --force origin HEAD && break || (echo "Push failed, retrying in 10 seconds..." && sleep 10)
        done

主要修改点说明：

1. Python-pip 安装：
   - 将原来的 
"sudo apt install -y python-pip" 改为更明确的 
"sudo apt install -y python3-pip"
   - 增加了 
"pip3 install --upgrade pip" 确保使用最新版 pip
2. 依赖安装命令：
   - 将 
"pip install requests" 改为 
"pip3 install requests" 确保使用 Python3 的 pip
   - 增加了 
"--upgrade" 参数确保 pip 保持最新状态
3. Python 脚本执行：
   - 显式使用 
"python3" 命令执行脚本（原代码中可能因环境变量问题导致使用 Python2）
4. 其他优化：
   - 将 
"git commit" 的错误处理改为 
"|| true" 防止空提交导致步骤失败
   - 使用 
"${{ secrets.GITHUB_TOKEN }}" 替代自定义 Token（更安全）
   - 增加重试机制提高文件推送可靠性

此修改确保：

✅ 正确安装 Python3-pip

✅ 使用 Python3 环境执行所有操作

✅ 避免因 pip 版本问题导致的依赖安装失败

✅ 更安全的密钥使用方式

✅ 更健壮的文件推送流程

如果仍然遇到问题，建议在 
"Install dependencies" 步骤中添加以下调试命令：

which python3
which pip3
pip3 --version

这将帮助确认 Python 和 pip 的实际路径及版本信息。
