name: Run_Adblock_Reject_JSON19  # Workflow name

on:
  schedule:
    - cron: '* * 2 * *'  # Run every 20 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu version as the runner

    steps:
    - name: Setup Node.js 20  # Set up Node.js 20 environment
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify Node.js version 20

    - name: Setup Python 3.9  # Set up Python 3.9 environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify Python version 3.9

    - name: Checkout repository  # Check out the code repository
      uses: actions/checkout@v3

    - name: Install dependencies and sing-box  # Install required dependencies and sing-box
      run: |
        sudo apt-get update  # Update package list
        sudo apt-get install -y wget apt-transport-https software-properties-common  # Install necessary packages
        wget https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box-1.11.15-linux-amd64.tar.gz
        tar -zxvf sing-box-1.11.15-linux-amd64.tar.gz
        sudo apt install -y bash
        rm sing-box-1.11.15-linux-amd64.tar.gz  # Clean up downloaded file

    - name: Run adblock_rule_generator_json19.py  # Run the Python script
      run: python3 adblock_rule_generator_json19.py  # Execute the Python script

    - name: Convert rule-set  # Convert rules using sing-box
      shell: bash
      run: sing-box-1.11.15-linux-amd64/sing-box rule-set compile --output adblock_reject19.srs adblock_reject19.json

    - name: Force Add and Commit adblock_rule_generator_json19.srs  # Force add and commit adblock_reject19.srs file
      run: |
        git config --global user.name 'github-actions'  # Configure commit username
        git config --global user.email 'github-actions@github.com'  # Configure commit email
        git add -f adblock_reject19.srs  # Force add adblock_reject19.srs file
        git commit -m 'Update adblock_reject19.srs' || git commit --allow-empty -m 'Empty commit to force push'  # Commit changes or empty commit if no changes

    - name: Retry Push SRS file  # Push adblock_reject19.srs file with retries
      env:
        TOKEN: ${{ secrets.TOKEN }}  # Use GitHub secret for authentication
      run: |
        for i in {1..5}; do  # Retry up to 5 times
          git push --force origin HEAD && exit 0 || (echo "Push failed, retrying in 10 seconds..." && sleep 10)
        done